/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[11] = 
  {0, 1, 2, 4, 6, 7, 8, 9,
  10, 11, 12};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {4, 1, 1};
static const casadi_int casadi_s6[3] = {13, 1, 1};
static const casadi_int casadi_s7[31] = 
  {12, 13, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 15,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 0, 1, 2, 5, 6, 8};
static const casadi_int casadi_s8[3] = {13, 0, 1};

/* frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt:(i0[9],i1[3],i2[0],i3[],i4[4])->(o0[13],o1[12x13,15nz],o2[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, *w10=w+10;
  casadi_real *w11=w+25, w12, w13, w14, w15, w16, w17, w18, w19, w21, *w22=w+44, *w23=w+55;
  casadi_real *w24=w+66, *w25=w+68;
  const casadi_int *cii;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][1] */
  w00 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #4: @0 = input[0][2] */
  w00 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #6: @1 = input[0][3] */
  w01 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @1 */
  if (res[0]) res[0][3] = w01;
  /* #8: @2 = input[0][4] */
  w02 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @2 */
  if (res[0]) res[0][4] = w02;
  /* #10: @2 = input[0][5] */
  w02 = arg[0] ? arg[0][5] : 0;
  /* #11: output[0][5] = @2 */
  if (res[0]) res[0][5] = w02;
  /* #12: @3 = input[0][6] */
  w03 = arg[0] ? arg[0][6] : 0;
  /* #13: output[0][6] = @3 */
  if (res[0]) res[0][6] = w03;
  /* #14: @3 = input[0][7] */
  w03 = arg[0] ? arg[0][7] : 0;
  /* #15: output[0][7] = @3 */
  if (res[0]) res[0][7] = w03;
  /* #16: @3 = input[0][8] */
  w03 = arg[0] ? arg[0][8] : 0;
  /* #17: output[0][8] = @3 */
  if (res[0]) res[0][8] = w03;
  /* #18: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #19: output[0][9] = @3 */
  if (res[0]) res[0][9] = w03;
  /* #20: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #21: output[0][10] = @3 */
  if (res[0]) res[0][10] = w03;
  /* #22: @3 = input[1][2] */
  w03 = arg[1] ? arg[1][2] : 0;
  /* #23: output[0][11] = @3 */
  if (res[0]) res[0][11] = w03;
  /* #24: @3 = 1e-08 */
  w03 = 1.0000000000000000e-08;
  /* #25: @4 = sq(@0) */
  w04 = casadi_sq( w00 );
  /* #26: @3 = (@3+@4) */
  w03 += w04;
  /* #27: @4 = sqrt(@3) */
  w04 = sqrt( w03 );
  /* #28: @5 = atan2(@1,@4) */
  w05  = atan2(w01,w04);
  /* #29: @6 = 0.792 */
  w06 = 7.9200000000000004e-01;
  /* #30: @7 = tan(@2) */
  w07 = tan( w02 );
  /* #31: @7 = (@6*@7) */
  w07  = (w06*w07);
  /* #32: @8 = 1.53 */
  w08 = 1.5300000000000000e+00;
  /* #33: @9 = atan2(@7,@8) */
  w09  = atan2(w07,w08);
  /* #34: @5 = (@5-@9) */
  w05 -= w09;
  /* #35: output[0][12] = @5 */
  if (res[0]) res[0][12] = w05;
  /* #36: @10 = zeros(12x13,15nz) */
  casadi_clear(w10, 15);
  /* #37: @11 = ones(12x1,10nz) */
  casadi_fill(w11, 10, 1.);
  /* #38: {@5, @9, @12, @13, @14, @15, NULL, @16, NULL, @17, @18, @19} = vertsplit(@11) */
  w05 = w11[0];
  w09 = w11[1];
  w12 = w11[2];
  w13 = w11[3];
  w14 = w11[4];
  w15 = w11[5];
  w16 = w11[6];
  w17 = w11[7];
  w18 = w11[8];
  w19 = w11[9];
  /* #39: @20 = 00 */
  /* #40: @21 = sq(@1) */
  w21 = casadi_sq( w01 );
  /* #41: @21 = (@21+@3) */
  w21 += w03;
  /* #42: @1 = (@1/@21) */
  w01 /= w21;
  /* #43: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #44: @0 = (@0*@15) */
  w00 *= w15;
  /* #45: @3 = (2.*@4) */
  w03 = (2.* w04 );
  /* #46: @0 = (@0/@3) */
  w00 /= w03;
  /* #47: @1 = (@1*@0) */
  w01 *= w00;
  /* #48: @1 = (-@1) */
  w01 = (- w01 );
  /* #49: @22 = vertcat(@13, @14, @15, @20, @16, @20, @17, @18, @19, @5, @9, @12, @1) */
  rr=w22;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w01;
  /* #50: @23 = @22[:11] */
  for (rr=w23, cs=w22+0; cs!=w22+11; cs+=1) *rr++ = *cs;
  /* #51: (@10[0, 1, 2, 4, 6, 7, 8, 9, 10, 11, 12] = @23) */
  for (cii=casadi_s0, rr=w10, cs=w23; cii!=casadi_s0+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #52: @13 = ones(12x1,1nz) */
  w13 = 1.;
  /* #53: {NULL, NULL, NULL, NULL, NULL, NULL, @14, NULL, NULL, NULL, NULL, NULL} = vertsplit(@13) */
  w14 = w13;
  /* #54: @4 = (@4/@21) */
  w04 /= w21;
  /* #55: @4 = (@4*@14) */
  w04 *= w14;
  /* #56: @24 = vertcat(@20, @20, @20, @14, @20, @20, @20, @20, @20, @20, @20, @20, @4) */
  rr=w24;
  *rr++ = w14;
  *rr++ = w04;
  /* #57: @25 = @24[:2] */
  for (rr=w25, cs=w24+0; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #58: (@10[3:23:10] = @25) */
  for (rr=w10+3, cs=w25; rr!=w10+23; rr+=10) *rr = *cs++;
  /* #59: @14 = ones(12x1,1nz) */
  w14 = 1.;
  /* #60: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @4, NULL, NULL, NULL} = vertsplit(@14) */
  w04 = w14;
  /* #61: @14 = 2.3409 */
  w14 = 2.3409000000000000e+00;
  /* #62: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #63: @14 = (@14+@7) */
  w14 += w07;
  /* #64: @8 = (@8/@14) */
  w08 /= w14;
  /* #65: @2 = cos(@2) */
  w02 = cos( w02 );
  /* #66: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #67: @2 = (@4/@2) */
  w02  = (w04/w02);
  /* #68: @6 = (@6*@2) */
  w06 *= w02;
  /* #69: @8 = (@8*@6) */
  w08 *= w06;
  /* #70: @8 = (-@8) */
  w08 = (- w08 );
  /* #71: @25 = vertcat(@20, @20, @20, @20, @20, @4, @20, @20, @20, @20, @20, @20, @8) */
  rr=w25;
  *rr++ = w04;
  *rr++ = w08;
  /* #72: @24 = @25[:2] */
  for (rr=w24, cs=w25+0; cs!=w25+2; cs+=1) *rr++ = *cs;
  /* #73: (@10[5:23:9] = @24) */
  for (rr=w10+5, cs=w24; rr!=w10+23; rr+=9) *rr = *cs++;
  /* #74: output[1][0] = @10 */
  casadi_copy(w10, 15, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 70;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 15*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 70*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
