/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {13, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};

/* frenet_centerline_runtime_constr_h_e_fun:(i0[9],i1[0],i2[0],i3[13])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = 1.44175 */
  w01 = 1.4417500000000001e+00;
  /* #2: @2 = 1e-08 */
  w02 = 1.0000000000000000e-08;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = sq(@3) */
  w04 = casadi_sq( w03 );
  /* #5: @4 = (@2+@4) */
  w04  = (w02+w04);
  /* #6: @4 = sqrt(@4) */
  w04 = sqrt( w04 );
  /* #7: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #8: @1 = (@1*@4) */
  w01 *= w04;
  /* #9: @4 = (@0+@1) */
  w04  = (w00+w01);
  /* #10: @5 = 0.7225 */
  w05 = 7.2250000000000003e-01;
  /* #11: @3 = cos(@3) */
  w03 = cos( w03 );
  /* #12: @5 = (@5*@3) */
  w05 *= w03;
  /* #13: @4 = (@4+@5) */
  w04 += w05;
  /* #14: @3 = 1.5 */
  w03 = 1.5000000000000000e+00;
  /* #15: @4 = (@4-@3) */
  w04 -= w03;
  /* #16: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #17: @1 = (@1-@0) */
  w01 -= w00;
  /* #18: @1 = (@1+@5) */
  w01 += w05;
  /* #19: @1 = (@1-@3) */
  w01 -= w03;
  /* #20: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #21: @1 = 2567 */
  w01 = 2567.;
  /* #22: @5 = input[0][8] */
  w05 = arg[0] ? arg[0][8] : 0;
  /* #23: @1 = (@1*@5) */
  w01 *= w05;
  /* #24: @5 = input[3][2] */
  w05 = arg[3] ? arg[3][2] : 0;
  /* #25: @0 = 1 */
  w00 = 1.;
  /* #26: @4 = 0.517647 */
  w04 = 5.1764705882352946e-01;
  /* #27: @6 = 1893.33 */
  w06 = 1.8933300000000002e+03;
  /* #28: @7 = 1.88 */
  w07 = 1.8799999999999999e+00;
  /* #29: @8 = input[0][2] */
  w08 = arg[0] ? arg[0][2] : 0;
  /* #30: @7 = (@7*@8) */
  w07 *= w08;
  /* #31: @7 = (@7*@8) */
  w07 *= w08;
  /* #32: @6 = (@6+@7) */
  w06 += w07;
  /* #33: @4 = (@4*@6) */
  w04 *= w06;
  /* #34: @7 = sq(@4) */
  w07 = casadi_sq( w04 );
  /* #35: @7 = (@0+@7) */
  w07  = (w00+w07);
  /* #36: @7 = sqrt(@7) */
  w07 = sqrt( w07 );
  /* #37: @9 = (@5*@7) */
  w09  = (w05*w07);
  /* #38: @9 = (@1/@9) */
  w09  = (w01/w09);
  /* #39: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #40: @10 = 1.737 */
  w10 = 1.7370000000000001e+00;
  /* #41: @4 = (@10*@4) */
  w04  = (w10*w04);
  /* #42: @11 = 10.23 */
  w11 = 1.0230000000000000e+01;
  /* #43: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #44: @13 = input[0][3] */
  w13 = arg[0] ? arg[0][3] : 0;
  /* #45: @14 = 0.738 */
  w14 = 7.3799999999999999e-01;
  /* #46: @15 = input[0][4] */
  w15 = arg[0] ? arg[0][4] : 0;
  /* #47: @14 = (@14*@15) */
  w14 *= w15;
  /* #48: @14 = (@13+@14) */
  w14  = (w13+w14);
  /* #49: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #50: @2 = (@2+@8) */
  w02 += w08;
  /* #51: @2 = sqrt(@2) */
  w02 = sqrt( w02 );
  /* #52: @14 = atan2(@14,@2) */
  w14  = atan2(w14,w02);
  /* #53: @12 = (@12-@14) */
  w12 -= w14;
  /* #54: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #55: @12 = atan2(@12,@0) */
  w12  = atan2(w12,w00);
  /* #56: @12 = (@3*@12) */
  w12  = (w03*w12);
  /* #57: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #58: @4 = (@4*@12) */
  w04 *= w12;
  /* #59: @12 = input[3][3] */
  w12 = arg[3] ? arg[3][3] : 0;
  /* #60: @7 = (@12*@7) */
  w07  = (w12*w07);
  /* #61: @4 = (@4/@7) */
  w04 /= w07;
  /* #62: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #63: @9 = (@9+@4) */
  w09 += w04;
  /* #64: @9 = (@9-@0) */
  w09 -= w00;
  /* #65: output[0][2] = @9 */
  if (res[0]) res[0][2] = w09;
  /* #66: @9 = 0.482353 */
  w09 = 4.8235294117647060e-01;
  /* #67: @9 = (@9*@6) */
  w09 *= w06;
  /* #68: @6 = sq(@9) */
  w06 = casadi_sq( w09 );
  /* #69: @6 = (@0+@6) */
  w06  = (w00+w06);
  /* #70: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #71: @5 = (@5*@6) */
  w05 *= w06;
  /* #72: @1 = (@1/@5) */
  w01 /= w05;
  /* #73: @1 = sq(@1) */
  w01 = casadi_sq( w01 );
  /* #74: @10 = (@10*@9) */
  w10 *= w09;
  /* #75: @9 = 0.792 */
  w09 = 7.9200000000000004e-01;
  /* #76: @9 = (@9*@15) */
  w09 *= w15;
  /* #77: @13 = (@13-@9) */
  w13 -= w09;
  /* #78: @13 = atan2(@13,@2) */
  w13  = atan2(w13,w02);
  /* #79: @11 = (@11*@13) */
  w11 *= w13;
  /* #80: @11 = (-@11) */
  w11 = (- w11 );
  /* #81: @11 = atan2(@11,@0) */
  w11  = atan2(w11,w00);
  /* #82: @3 = (@3*@11) */
  w03 *= w11;
  /* #83: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #84: @10 = (@10*@3) */
  w10 *= w03;
  /* #85: @12 = (@12*@6) */
  w12 *= w06;
  /* #86: @10 = (@10/@12) */
  w10 /= w12;
  /* #87: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #88: @1 = (@1+@10) */
  w01 += w10;
  /* #89: @1 = (@1-@0) */
  w01 -= w00;
  /* #90: output[0][3] = @1 */
  if (res[0]) res[0][3] = w01;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_constr_h_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_constr_h_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_constr_h_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 16*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
