/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {13, 1, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[20] = 
  {12, 4, 0, 2, 4, 9, 13, 3,
  4, 3, 4, 5, 6, 7, 8, 11,
  5, 6, 7, 11};
static const casadi_int casadi_s6[3] = {4, 0, 1};

/* frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt:(i0[9],i1[3],i2[0],i3[13])->(o0[4],o1[12x4,13nz],o2[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34;
  casadi_real w35, w36, w37, w38, w39, w40, w41, w42, w43, *w44=w+44, *w45=w+57, w46;
  casadi_real w47, w48, w49, w50;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = 1.44175 */
  w01 = 1.4417500000000001e+00;
  /* #2: @2 = 1e-08 */
  w02 = 1.0000000000000000e-08;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = sq(@3) */
  w04 = casadi_sq( w03 );
  /* #5: @4 = (@2+@4) */
  w04  = (w02+w04);
  /* #6: @4 = sqrt(@4) */
  w04 = sqrt( w04 );
  /* #7: @5 = sin(@4) */
  w05 = sin( w04 );
  /* #8: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #9: @6 = (@0+@5) */
  w06  = (w00+w05);
  /* #10: @7 = 0.7225 */
  w07 = 7.2250000000000003e-01;
  /* #11: @8 = cos(@3) */
  w08 = cos( w03 );
  /* #12: @8 = (@7*@8) */
  w08  = (w07*w08);
  /* #13: @6 = (@6+@8) */
  w06 += w08;
  /* #14: @9 = 1.5 */
  w09 = 1.5000000000000000e+00;
  /* #15: @6 = (@6-@9) */
  w06 -= w09;
  /* #16: output[0][0] = @6 */
  if (res[0]) res[0][0] = w06;
  /* #17: @5 = (@5-@0) */
  w05 -= w00;
  /* #18: @5 = (@5+@8) */
  w05 += w08;
  /* #19: @5 = (@5-@9) */
  w05 -= w09;
  /* #20: output[0][1] = @5 */
  if (res[0]) res[0][1] = w05;
  /* #21: @5 = 2567 */
  w05 = 2567.;
  /* #22: @8 = input[0][8] */
  w08 = arg[0] ? arg[0][8] : 0;
  /* #23: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #24: @0 = input[3][2] */
  w00 = arg[3] ? arg[3][2] : 0;
  /* #25: @6 = 1 */
  w06 = 1.;
  /* #26: @10 = 0.517647 */
  w10 = 5.1764705882352946e-01;
  /* #27: @11 = 1893.33 */
  w11 = 1.8933300000000002e+03;
  /* #28: @12 = 1.88 */
  w12 = 1.8799999999999999e+00;
  /* #29: @13 = input[0][2] */
  w13 = arg[0] ? arg[0][2] : 0;
  /* #30: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #31: @15 = (@14*@13) */
  w15  = (w14*w13);
  /* #32: @11 = (@11+@15) */
  w11 += w15;
  /* #33: @15 = (@10*@11) */
  w15  = (w10*w11);
  /* #34: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #35: @16 = (@6+@16) */
  w16  = (w06+w16);
  /* #36: @16 = sqrt(@16) */
  w16 = sqrt( w16 );
  /* #37: @17 = (@0*@16) */
  w17  = (w00*w16);
  /* #38: @18 = (@8/@17) */
  w18  = (w08/w17);
  /* #39: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #40: @20 = 1.737 */
  w20 = 1.7370000000000001e+00;
  /* #41: @21 = (@20*@15) */
  w21  = (w20*w15);
  /* #42: @22 = 10.23 */
  w22 = 1.0230000000000000e+01;
  /* #43: @23 = input[0][5] */
  w23 = arg[0] ? arg[0][5] : 0;
  /* #44: @24 = input[0][3] */
  w24 = arg[0] ? arg[0][3] : 0;
  /* #45: @25 = 0.738 */
  w25 = 7.3799999999999999e-01;
  /* #46: @26 = input[0][4] */
  w26 = arg[0] ? arg[0][4] : 0;
  /* #47: @27 = (@25*@26) */
  w27  = (w25*w26);
  /* #48: @27 = (@24+@27) */
  w27  = (w24+w27);
  /* #49: @28 = sq(@13) */
  w28 = casadi_sq( w13 );
  /* #50: @2 = (@2+@28) */
  w02 += w28;
  /* #51: @28 = sqrt(@2) */
  w28 = sqrt( w02 );
  /* #52: @29 = atan2(@27,@28) */
  w29  = atan2(w27,w28);
  /* #53: @23 = (@23-@29) */
  w23 -= w29;
  /* #54: @23 = (@22*@23) */
  w23  = (w22*w23);
  /* #55: @29 = atan2(@23,@6) */
  w29  = atan2(w23,w06);
  /* #56: @29 = (@9*@29) */
  w29  = (w09*w29);
  /* #57: @30 = sin(@29) */
  w30 = sin( w29 );
  /* #58: @31 = (@21*@30) */
  w31  = (w21*w30);
  /* #59: @32 = input[3][3] */
  w32 = arg[3] ? arg[3][3] : 0;
  /* #60: @33 = (@32*@16) */
  w33  = (w32*w16);
  /* #61: @31 = (@31/@33) */
  w31 /= w33;
  /* #62: @34 = sq(@31) */
  w34 = casadi_sq( w31 );
  /* #63: @19 = (@19+@34) */
  w19 += w34;
  /* #64: @19 = (@19-@6) */
  w19 -= w06;
  /* #65: output[0][2] = @19 */
  if (res[0]) res[0][2] = w19;
  /* #66: @19 = 0.482353 */
  w19 = 4.8235294117647060e-01;
  /* #67: @11 = (@19*@11) */
  w11  = (w19*w11);
  /* #68: @34 = sq(@11) */
  w34 = casadi_sq( w11 );
  /* #69: @34 = (@6+@34) */
  w34  = (w06+w34);
  /* #70: @34 = sqrt(@34) */
  w34 = sqrt( w34 );
  /* #71: @35 = (@0*@34) */
  w35  = (w00*w34);
  /* #72: @8 = (@8/@35) */
  w08 /= w35;
  /* #73: @36 = sq(@8) */
  w36 = casadi_sq( w08 );
  /* #74: @37 = (@20*@11) */
  w37  = (w20*w11);
  /* #75: @38 = 0.792 */
  w38 = 7.9200000000000004e-01;
  /* #76: @26 = (@38*@26) */
  w26  = (w38*w26);
  /* #77: @24 = (@24-@26) */
  w24 -= w26;
  /* #78: @26 = atan2(@24,@28) */
  w26  = atan2(w24,w28);
  /* #79: @26 = (@22*@26) */
  w26  = (w22*w26);
  /* #80: @39 = (-@26) */
  w39 = (- w26 );
  /* #81: @39 = atan2(@39,@6) */
  w39  = atan2(w39,w06);
  /* #82: @39 = (@9*@39) */
  w39  = (w09*w39);
  /* #83: @40 = sin(@39) */
  w40 = sin( w39 );
  /* #84: @41 = (@37*@40) */
  w41  = (w37*w40);
  /* #85: @42 = (@32*@34) */
  w42  = (w32*w34);
  /* #86: @41 = (@41/@42) */
  w41 /= w42;
  /* #87: @43 = sq(@41) */
  w43 = casadi_sq( w41 );
  /* #88: @36 = (@36+@43) */
  w36 += w43;
  /* #89: @36 = (@36-@6) */
  w36 -= w06;
  /* #90: output[0][3] = @36 */
  if (res[0]) res[0][3] = w36;
  /* #91: @44 = zeros(12x4,13nz) */
  casadi_clear(w44, 13);
  /* #92: @45 = ones(4x1,2nz) */
  casadi_fill(w45, 2, 1.);
  /* #93: {@36, NULL, @43, NULL} = vertsplit(@45) */
  w36 = w45[0];
  w43 = w45[1];
  /* #94: (@44[0] = @36) */
  for (rr=w44+0, cs=(&w36); rr!=w44+1; rr+=1) *rr = *cs++;
  /* #95: @46 = (2.*@3) */
  w46 = (2.* w03 );
  /* #96: @47 = cos(@4) */
  w47 = cos( w04 );
  /* #97: @48 = (@1*@36) */
  w48  = (w01*w36);
  /* #98: @48 = (@47*@48) */
  w48  = (w47*w48);
  /* #99: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #100: @48 = (@48/@4) */
  w48 /= w04;
  /* #101: @48 = (@46*@48) */
  w48  = (w46*w48);
  /* #102: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #103: @36 = (@7*@36) */
  w36  = (w07*w36);
  /* #104: @36 = (@3*@36) */
  w36  = (w03*w36);
  /* #105: @48 = (@48-@36) */
  w48 -= w36;
  /* #106: (@44[1] = @48) */
  for (rr=w44+1, cs=(&w48); rr!=w44+2; rr+=1) *rr = *cs++;
  /* #107: @48 = (2.*@13) */
  w48 = (2.* w13 );
  /* #108: @36 = sq(@27) */
  w36 = casadi_sq( w27 );
  /* #109: @36 = (@36+@2) */
  w36 += w02;
  /* #110: @27 = (@27/@36) */
  w27 /= w36;
  /* #111: @29 = cos(@29) */
  w29 = cos( w29 );
  /* #112: @49 = (2.*@31) */
  w49 = (2.* w31 );
  /* #113: @49 = (@49*@43) */
  w49 *= w43;
  /* #114: @50 = (@49/@33) */
  w50  = (w49/w33);
  /* #115: @21 = (@21*@50) */
  w21 *= w50;
  /* #116: @29 = (@29*@21) */
  w29 *= w21;
  /* #117: @29 = (@9*@29) */
  w29  = (w09*w29);
  /* #118: @23 = sq(@23) */
  w23 = casadi_sq( w23 );
  /* #119: @23 = (@6+@23) */
  w23  = (w06+w23);
  /* #120: @29 = (@29/@23) */
  w29 /= w23;
  /* #121: @29 = (@22*@29) */
  w29  = (w22*w29);
  /* #122: @27 = (@27*@29) */
  w27 *= w29;
  /* #123: @23 = (2.*@28) */
  w23 = (2.* w28 );
  /* #124: @27 = (@27/@23) */
  w27 /= w23;
  /* #125: @27 = (@48*@27) */
  w27  = (w48*w27);
  /* #126: @30 = (@30*@50) */
  w30 *= w50;
  /* #127: @30 = (@20*@30) */
  w30  = (w20*w30);
  /* #128: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #129: @50 = (@18/@17) */
  w50  = (w18/w17);
  /* #130: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #131: @18 = (@18*@43) */
  w18 *= w43;
  /* #132: @50 = (@50*@18) */
  w50 *= w18;
  /* #133: @50 = (@0*@50) */
  w50  = (w00*w50);
  /* #134: @50 = (-@50) */
  w50 = (- w50 );
  /* #135: @31 = (@31/@33) */
  w31 /= w33;
  /* #136: @31 = (@31*@49) */
  w31 *= w49;
  /* #137: @31 = (@32*@31) */
  w31  = (w32*w31);
  /* #138: @50 = (@50-@31) */
  w50 -= w31;
  /* #139: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #140: @50 = (@50/@16) */
  w50 /= w16;
  /* #141: @15 = (@15*@50) */
  w15 *= w50;
  /* #142: @30 = (@30+@15) */
  w30 += w15;
  /* #143: @10 = (@10*@30) */
  w10 *= w30;
  /* #144: @30 = (@14*@10) */
  w30  = (w14*w10);
  /* #145: @27 = (@27+@30) */
  w27 += w30;
  /* #146: @10 = (@13*@10) */
  w10  = (w13*w10);
  /* #147: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #148: @27 = (@27+@10) */
  w27 += w10;
  /* #149: (@44[4] = @27) */
  for (rr=w44+4, cs=(&w27); rr!=w44+5; rr+=1) *rr = *cs++;
  /* #150: @36 = (@28/@36) */
  w36  = (w28/w36);
  /* #151: @36 = (@36*@29) */
  w36 *= w29;
  /* #152: @27 = (-@36) */
  w27 = (- w36 );
  /* #153: (@44[5] = @27) */
  for (rr=w44+5, cs=(&w27); rr!=w44+6; rr+=1) *rr = *cs++;
  /* #154: @25 = (@25*@36) */
  w25 *= w36;
  /* #155: @25 = (-@25) */
  w25 = (- w25 );
  /* #156: (@44[6] = @25) */
  for (rr=w44+6, cs=(&w25); rr!=w44+7; rr+=1) *rr = *cs++;
  /* #157: (@44[7] = @29) */
  for (rr=w44+7, cs=(&w29); rr!=w44+8; rr+=1) *rr = *cs++;
  /* #158: @18 = (@18/@17) */
  w18 /= w17;
  /* #159: @18 = (@5*@18) */
  w18  = (w05*w18);
  /* #160: (@44[8] = @18) */
  for (rr=w44+8, cs=(&w18); rr!=w44+9; rr+=1) *rr = *cs++;
  /* #161: @45 = ones(4x1,2nz) */
  casadi_fill(w45, 2, 1.);
  /* #162: {NULL, @18, NULL, @17} = vertsplit(@45) */
  w18 = w45[0];
  w17 = w45[1];
  /* #163: @29 = (-@18) */
  w29 = (- w18 );
  /* #164: (@44[2] = @29) */
  for (rr=w44+2, cs=(&w29); rr!=w44+3; rr+=1) *rr = *cs++;
  /* #165: @1 = (@1*@18) */
  w01 *= w18;
  /* #166: @47 = (@47*@1) */
  w47 *= w01;
  /* #167: @47 = (@47/@4) */
  w47 /= w04;
  /* #168: @46 = (@46*@47) */
  w46 *= w47;
  /* #169: @7 = (@7*@18) */
  w07 *= w18;
  /* #170: @3 = (@3*@7) */
  w03 *= w07;
  /* #171: @46 = (@46-@3) */
  w46 -= w03;
  /* #172: (@44[3] = @46) */
  for (rr=w44+3, cs=(&w46); rr!=w44+4; rr+=1) *rr = *cs++;
  /* #173: @46 = sq(@24) */
  w46 = casadi_sq( w24 );
  /* #174: @46 = (@46+@2) */
  w46 += w02;
  /* #175: @24 = (@24/@46) */
  w24 /= w46;
  /* #176: @39 = cos(@39) */
  w39 = cos( w39 );
  /* #177: @2 = (2.*@41) */
  w02 = (2.* w41 );
  /* #178: @2 = (@2*@17) */
  w02 *= w17;
  /* #179: @3 = (@2/@42) */
  w03  = (w02/w42);
  /* #180: @37 = (@37*@3) */
  w37 *= w03;
  /* #181: @39 = (@39*@37) */
  w39 *= w37;
  /* #182: @9 = (@9*@39) */
  w09 *= w39;
  /* #183: @26 = sq(@26) */
  w26 = casadi_sq( w26 );
  /* #184: @6 = (@6+@26) */
  w06 += w26;
  /* #185: @9 = (@9/@6) */
  w09 /= w06;
  /* #186: @22 = (@22*@9) */
  w22 *= w09;
  /* #187: @24 = (@24*@22) */
  w24 *= w22;
  /* #188: @24 = (@24/@23) */
  w24 /= w23;
  /* #189: @48 = (@48*@24) */
  w48 *= w24;
  /* #190: @40 = (@40*@3) */
  w40 *= w03;
  /* #191: @20 = (@20*@40) */
  w20 *= w40;
  /* #192: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #193: @40 = (@8/@35) */
  w40  = (w08/w35);
  /* #194: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #195: @8 = (@8*@17) */
  w08 *= w17;
  /* #196: @40 = (@40*@8) */
  w40 *= w08;
  /* #197: @0 = (@0*@40) */
  w00 *= w40;
  /* #198: @0 = (-@0) */
  w00 = (- w00 );
  /* #199: @41 = (@41/@42) */
  w41 /= w42;
  /* #200: @41 = (@41*@2) */
  w41 *= w02;
  /* #201: @32 = (@32*@41) */
  w32 *= w41;
  /* #202: @0 = (@0-@32) */
  w00 -= w32;
  /* #203: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #204: @0 = (@0/@34) */
  w00 /= w34;
  /* #205: @11 = (@11*@0) */
  w11 *= w00;
  /* #206: @20 = (@20+@11) */
  w20 += w11;
  /* #207: @19 = (@19*@20) */
  w19 *= w20;
  /* #208: @14 = (@14*@19) */
  w14 *= w19;
  /* #209: @48 = (@48+@14) */
  w48 += w14;
  /* #210: @13 = (@13*@19) */
  w13 *= w19;
  /* #211: @12 = (@12*@13) */
  w12 *= w13;
  /* #212: @48 = (@48+@12) */
  w48 += w12;
  /* #213: (@44[9] = @48) */
  for (rr=w44+9, cs=(&w48); rr!=w44+10; rr+=1) *rr = *cs++;
  /* #214: @28 = (@28/@46) */
  w28 /= w46;
  /* #215: @28 = (@28*@22) */
  w28 *= w22;
  /* #216: @22 = (-@28) */
  w22 = (- w28 );
  /* #217: (@44[10] = @22) */
  for (rr=w44+10, cs=(&w22); rr!=w44+11; rr+=1) *rr = *cs++;
  /* #218: @38 = (@38*@28) */
  w38 *= w28;
  /* #219: (@44[11] = @38) */
  for (rr=w44+11, cs=(&w38); rr!=w44+12; rr+=1) *rr = *cs++;
  /* #220: @8 = (@8/@35) */
  w08 /= w35;
  /* #221: @5 = (@5*@8) */
  w05 *= w08;
  /* #222: (@44[12] = @5) */
  for (rr=w44+12, cs=(&w05); rr!=w44+13; rr+=1) *rr = *cs++;
  /* #223: output[1][0] = @44 */
  casadi_copy(w44, 13, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 64;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_constr_h_0_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 64*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
