/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_conl_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {7, 1, 1};
static const casadi_int casadi_s4[3] = {0, 0, 1};
static const casadi_int casadi_s5[3] = {13, 1, 1};
static const casadi_int casadi_s6[3] = {1, 1, 1};

/* psi:(i0[7],i1[],i2[13],i3[0])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, w1, *w2=w+2, w3;
  const casadi_real *cs;
  /* #0: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #1: @1 = input[2][4] */
  w1 = arg[2] ? arg[2][4] : 0;
  /* #2: @0 = (@0*@1) */
  w0 *= w1;
  /* #3: @2 = input[0][0] */
  casadi_copy(arg[0], 7, w2);
  /* #4: @1 = @2[0] */
  for (rr=(&w1), cs=w2+0; cs!=w2+1; cs+=1) *rr++ = *cs;
  /* #5: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #6: @0 = (@0*@1) */
  w0 *= w1;
  /* #7: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #8: @3 = input[2][5] */
  w3 = arg[2] ? arg[2][5] : 0;
  /* #9: @1 = (@1*@3) */
  w1 *= w3;
  /* #10: @3 = @2[1] */
  for (rr=(&w3), cs=w2+1; cs!=w2+2; cs+=1) *rr++ = *cs;
  /* #11: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #12: @1 = (@1*@3) */
  w1 *= w3;
  /* #13: @0 = (@0+@1) */
  w0 += w1;
  /* #14: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #15: @3 = input[2][6] */
  w3 = arg[2] ? arg[2][6] : 0;
  /* #16: @1 = (@1*@3) */
  w1 *= w3;
  /* #17: @3 = @2[2] */
  for (rr=(&w3), cs=w2+2; cs!=w2+3; cs+=1) *rr++ = *cs;
  /* #18: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #19: @1 = (@1*@3) */
  w1 *= w3;
  /* #20: @0 = (@0+@1) */
  w0 += w1;
  /* #21: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #22: @3 = input[2][7] */
  w3 = arg[2] ? arg[2][7] : 0;
  /* #23: @1 = (@1*@3) */
  w1 *= w3;
  /* #24: @3 = @2[3] */
  for (rr=(&w3), cs=w2+3; cs!=w2+4; cs+=1) *rr++ = *cs;
  /* #25: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #26: @1 = (@1*@3) */
  w1 *= w3;
  /* #27: @0 = (@0+@1) */
  w0 += w1;
  /* #28: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #29: @3 = input[2][8] */
  w3 = arg[2] ? arg[2][8] : 0;
  /* #30: @1 = (@1*@3) */
  w1 *= w3;
  /* #31: @3 = @2[4] */
  for (rr=(&w3), cs=w2+4; cs!=w2+5; cs+=1) *rr++ = *cs;
  /* #32: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #33: @1 = (@1*@3) */
  w1 *= w3;
  /* #34: @0 = (@0+@1) */
  w0 += w1;
  /* #35: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #36: @3 = input[2][9] */
  w3 = arg[2] ? arg[2][9] : 0;
  /* #37: @1 = (@1*@3) */
  w1 *= w3;
  /* #38: @3 = @2[5] */
  for (rr=(&w3), cs=w2+5; cs!=w2+6; cs+=1) *rr++ = *cs;
  /* #39: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #40: @1 = (@1*@3) */
  w1 *= w3;
  /* #41: @0 = (@0+@1) */
  w0 += w1;
  /* #42: @1 = input[2][10] */
  w1 = arg[2] ? arg[2][10] : 0;
  /* #43: @3 = @2[6] */
  for (rr=(&w3), cs=w2+6; cs!=w2+7; cs+=1) *rr++ = *cs;
  /* #44: @1 = (@1*@3) */
  w1 *= w3;
  /* #45: @0 = (@0-@1) */
  w0 -= w1;
  /* #46: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* frenet_centerline_runtime_conl_cost_fun:(i0[9],i1[3],i2[0],i3[7],i4[],i5[13])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real *w10=w+20, *w11=w+27, w13, w14, w15, *w16=w+37;
  const casadi_real **arg1=arg+6, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[1][0] */
  w02 = arg[1] ? arg[1][0] : 0;
  /* #3: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #4: @4 = input[1][2] */
  w04 = arg[1] ? arg[1][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = 1e-08 */
  w06 = 1.0000000000000000e-08;
  /* #7: @7 = input[0][2] */
  w07 = arg[0] ? arg[0][2] : 0;
  /* #8: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #9: @6 = (@6+@8) */
  w06 += w08;
  /* #10: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #11: @6 = atan2(@5,@6) */
  w06  = atan2(w05,w06);
  /* #12: @8 = 0.792 */
  w08 = 7.9200000000000004e-01;
  /* #13: @9 = input[0][5] */
  w09 = arg[0] ? arg[0][5] : 0;
  /* #14: @9 = tan(@9) */
  w09 = tan( w09 );
  /* #15: @8 = (@8*@9) */
  w08 *= w09;
  /* #16: @9 = 1.53 */
  w09 = 1.5300000000000000e+00;
  /* #17: @8 = atan2(@8,@9) */
  w08  = atan2(w08,w09);
  /* #18: @6 = (@6-@8) */
  w06 -= w08;
  /* #19: @8 = cos(@1) */
  w08 = cos( w01 );
  /* #20: @7 = (@7*@8) */
  w07 *= w08;
  /* #21: @8 = sin(@1) */
  w08 = sin( w01 );
  /* #22: @5 = (@5*@8) */
  w05 *= w08;
  /* #23: @7 = (@7-@5) */
  w07 -= w05;
  /* #24: @5 = 1 */
  w05 = 1.;
  /* #25: @8 = input[5][0] */
  w08 = arg[5] ? arg[5][0] : 0;
  /* #26: @9 = (@0*@8) */
  w09  = (w00*w08);
  /* #27: @5 = (@5-@9) */
  w05 -= w09;
  /* #28: @7 = (@7/@5) */
  w07 /= w05;
  /* #29: @10 = vertcat(@0, @1, @2, @3, @4, @6, @7) */
  rr=w10;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w07;
  /* #30: @11 = input[3][0] */
  casadi_copy(arg[3], 7, w11);
  /* #31: @10 = (@10-@11) */
  for (i=0, rr=w10, cs=w11; i<7; ++i) (*rr++) -= (*cs++);
  /* #32: @12 = 0x0 */
  /* #33: @0 = input[5][1] */
  w00 = arg[5] ? arg[5][1] : 0;
  /* #34: @1 = input[5][2] */
  w01 = arg[5] ? arg[5][2] : 0;
  /* #35: @2 = input[5][3] */
  w02 = arg[5] ? arg[5][3] : 0;
  /* #36: @3 = input[5][4] */
  w03 = arg[5] ? arg[5][4] : 0;
  /* #37: @4 = input[5][5] */
  w04 = arg[5] ? arg[5][5] : 0;
  /* #38: @6 = input[5][6] */
  w06 = arg[5] ? arg[5][6] : 0;
  /* #39: @7 = input[5][7] */
  w07 = arg[5] ? arg[5][7] : 0;
  /* #40: @5 = input[5][8] */
  w05 = arg[5] ? arg[5][8] : 0;
  /* #41: @9 = input[5][9] */
  w09 = arg[5] ? arg[5][9] : 0;
  /* #42: @13 = input[5][10] */
  w13 = arg[5] ? arg[5][10] : 0;
  /* #43: @14 = input[5][11] */
  w14 = arg[5] ? arg[5][11] : 0;
  /* #44: @15 = input[5][12] */
  w15 = arg[5] ? arg[5][12] : 0;
  /* #45: @16 = vertcat(@8, @0, @1, @2, @3, @4, @6, @7, @5, @9, @13, @14, @15) */
  rr=w16;
  *rr++ = w08;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w05;
  *rr++ = w09;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #46: @17 = 0x1 */
  /* #47: @8 = psi(@10, @12, @16, @17) */
  arg1[0]=w10;
  arg1[1]=0;
  arg1[2]=w16;
  arg1[3]=0;
  res1[0]=(&w08);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #48: output[0][0] = @8 */
  if (res[0]) res[0][0] = w08;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_conl_cost_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_conl_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_conl_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_conl_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_conl_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_conl_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_conl_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 50;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 50*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
