/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[20] = 
  {12, 12, 0, 0, 0, 0, 0, 0,
  2, 4, 4, 5, 5, 5, 5, 5,
  6, 5, 6, 8};
static const casadi_int casadi_s1[3] = {9, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};
static const casadi_int casadi_s4[3] = {13, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};
static const casadi_int casadi_s6[3] = {4, 1, 1};

static const casadi_real casadi_zeros[13] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* frenet_centerline_runtime_cost_y_hess:(i0[9],i1[3],i2[0],i3[13],i4[],i5[4])->(o0[12x12,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w00=w+0, w02, w03, w04, w05, w06, w08, w09, w10, *w11=w+26, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+47, *w23=w+50, *w24=w+53;
  casadi_real *w25=w+55, *w26=w+57;
  const casadi_real *cs, *wr07;
  /* #0: @0 = zeros(12x12,5nz) */
  casadi_clear(w00, 5);
  /* #1: @1 = 00 */
  /* #2: @2 = input[0][3] */
  w02 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = sq(@2) */
  w03 = casadi_sq( w02 );
  /* #4: @4 = 1e-08 */
  w04 = 1.0000000000000000e-08;
  /* #5: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #6: @6 = sq(@5) */
  w06 = casadi_sq( w05 );
  /* #7: @4 = (@4+@6) */
  w04 += w06;
  /* #8: @3 = (@3+@4) */
  w03 += w04;
  /* #9: @6 = (@2/@3) */
  w06  = (w02/w03);
  /* #10: @7 = input[3][0] */
  wr07 = arg[3] ? arg[3] : casadi_zeros;
  /* #11: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @8} = vertsplit(@7) */
  w08 = wr07[12];
  /* #12: @9 = (@6*@8) */
  w09  = (w06*w08);
  /* #13: @4 = sqrt(@4) */
  w04 = sqrt( w04 );
  /* #14: @10 = (2.*@4) */
  w10 = (2.* w04 );
  /* #15: @9 = (@9/@10) */
  w09 /= w10;
  /* #16: @11 = ones(12x1,11nz) */
  casadi_fill(w11, 11, 1.);
  /* #17: {NULL, NULL, NULL, NULL, NULL, @12, NULL, NULL, @13, NULL, NULL, NULL} = vertsplit(@11) */
  w12 = w11[5];
  w13 = w11[7];
  /* #18: @14 = (2.*@12) */
  w14 = (2.* w12 );
  /* #19: @14 = (@9*@14) */
  w14  = (w09*w14);
  /* #20: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #21: @9 = (@9/@10) */
  w09 /= w10;
  /* #22: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #23: @15 = (@12/@10) */
  w15  = (w12/w10);
  /* #24: @16 = (2.*@15) */
  w16 = (2.* w15 );
  /* #25: @9 = (@9*@16) */
  w09 *= w16;
  /* #26: @9 = (-@9) */
  w09 = (- w09 );
  /* #27: @6 = (@6/@3) */
  w06 /= w03;
  /* #28: @16 = (@6*@12) */
  w16  = (w06*w12);
  /* #29: @16 = (@8*@16) */
  w16  = (w08*w16);
  /* #30: @16 = (@16/@10) */
  w16 /= w10;
  /* #31: @9 = (@9-@16) */
  w09 -= w16;
  /* #32: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #33: @14 = (@14+@9) */
  w14 += w09;
  /* #34: @14 = (-@14) */
  w14 = (- w14 );
  /* #35: @15 = (@15/@3) */
  w15 /= w03;
  /* #36: @4 = (@4/@3) */
  w04 /= w03;
  /* #37: @4 = (@4/@3) */
  w04 /= w03;
  /* #38: @12 = (@4*@12) */
  w12  = (w04*w12);
  /* #39: @15 = (@15-@12) */
  w15 -= w12;
  /* #40: @15 = (@8*@15) */
  w15  = (w08*w15);
  /* #41: @12 = 0.792 */
  w12 = 7.9200000000000004e-01;
  /* #42: @9 = 1.53 */
  w09 = 1.5300000000000000e+00;
  /* #43: @16 = 2.3409 */
  w16 = 2.3409000000000000e+00;
  /* #44: @17 = input[0][5] */
  w17 = arg[0] ? arg[0][5] : 0;
  /* #45: @18 = tan(@17) */
  w18 = tan( w17 );
  /* #46: @18 = (@12*@18) */
  w18  = (w12*w18);
  /* #47: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #48: @16 = (@16+@19) */
  w16 += w19;
  /* #49: @9 = (@9/@16) */
  w09 /= w16;
  /* #50: @19 = (@9*@8) */
  w19  = (w09*w08);
  /* #51: @19 = (@12*@19) */
  w19  = (w12*w19);
  /* #52: @20 = cos(@17) */
  w20 = cos( w17 );
  /* #53: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #54: @19 = (@19/@21) */
  w19 /= w21;
  /* #55: @19 = (@19/@21) */
  w19 /= w21;
  /* #56: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #57: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #58: @17 = (@17*@13) */
  w17 *= w13;
  /* #59: @20 = (@20*@17) */
  w20 *= w17;
  /* #60: @19 = (@19*@20) */
  w19 *= w20;
  /* #61: @9 = (@9/@16) */
  w09 /= w16;
  /* #62: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #63: @13 = (@13/@21) */
  w13 /= w21;
  /* #64: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #65: @18 = (@18*@13) */
  w18 *= w13;
  /* #66: @9 = (@9*@18) */
  w09 *= w18;
  /* #67: @9 = (@8*@9) */
  w09  = (w08*w09);
  /* #68: @12 = (@12*@9) */
  w12 *= w09;
  /* #69: @12 = (@12/@21) */
  w12 /= w21;
  /* #70: @19 = (@19-@12) */
  w19 -= w12;
  /* #71: @19 = (-@19) */
  w19 = (- w19 );
  /* #72: @22 = vertcat(@1, @1, @1, @1, @1, @14, @15, @1, @19, @1, @1, @1) */
  rr=w22;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w19;
  /* #73: @23 = @22[:3] */
  for (rr=w23, cs=w22+0; cs!=w22+3; cs+=1) *rr++ = *cs;
  /* #74: (@0[:6:2] = @23) */
  for (rr=w00+0, cs=w23; rr!=w00+6; rr+=2) *rr = *cs++;
  /* #75: @14 = ones(12x1,1nz) */
  w14 = 1.;
  /* #76: {NULL, NULL, NULL, NULL, NULL, NULL, @15, NULL, NULL, NULL, NULL, NULL} = vertsplit(@14) */
  w15 = w14;
  /* #77: @3 = (@15/@3) */
  w03  = (w15/w03);
  /* #78: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #79: @2 = (@2*@15) */
  w02 *= w15;
  /* #80: @6 = (@6*@2) */
  w06 *= w02;
  /* #81: @3 = (@3-@6) */
  w03 -= w06;
  /* #82: @3 = (@8*@3) */
  w03  = (w08*w03);
  /* #83: @3 = (@3/@10) */
  w03 /= w10;
  /* #84: @5 = (@5*@3) */
  w05 *= w03;
  /* #85: @5 = (-@5) */
  w05 = (- w05 );
  /* #86: @4 = (@4*@2) */
  w04 *= w02;
  /* #87: @8 = (@8*@4) */
  w08 *= w04;
  /* #88: @8 = (-@8) */
  w08 = (- w08 );
  /* #89: @24 = vertcat(@1, @1, @1, @1, @1, @5, @8, @1, @1, @1, @1, @1) */
  rr=w24;
  *rr++ = w05;
  *rr++ = w08;
  /* #90: @25 = @24[:2] */
  for (rr=w25, cs=w24+0; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #91: (@0[1:5:2] = @25) */
  for (rr=w00+1, cs=w25; rr!=w00+5; rr+=2) *rr = *cs++;
  /* #92: @26 = @0' */
  casadi_trans(w00,casadi_s0, w26, casadi_s0, iw);
  /* #93: output[0][0] = @26 */
  casadi_copy(w26, 5, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    case 5: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 62;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 14*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 13*sizeof(casadi_int);
  if (sz_w) *sz_w = 62*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
