/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {13, 1, 1};

/* frenet_centerline_runtime_dyn_disc_phi_fun:(i0[9],i1[3],i2[13])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, *w09=w+9, w10;
  casadi_real w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  casadi_real w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34;
  casadi_real w35, *w36=w+44;
  const casadi_real *cr, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w04 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w06 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = input[0][7] */
  w07 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = input[0][8] */
  w08 = arg[0] ? arg[0][8] : 0;
  /* #9: @9 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8) */
  rr=w09;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  /* #10: @10 = 0.0333333 */
  w10 = 3.3333333333333333e-02;
  /* #11: @11 = 0.0166667 */
  w11 = 1.6666666666666666e-02;
  /* #12: @12 = sin(@1) */
  w12 = sin( w01 );
  /* #13: @13 = (@2*@12) */
  w13  = (w02*w12);
  /* #14: @1 = cos(@1) */
  w01 = cos( w01 );
  /* #15: @14 = (@3*@1) */
  w14  = (w03*w01);
  /* #16: @13 = (@13+@14) */
  w13 += w14;
  /* #17: @14 = input[2][0] */
  w14 = arg[2] ? arg[2][0] : 0;
  /* #18: @1 = (@2*@1) */
  w01  = (w02*w01);
  /* #19: @12 = (@3*@12) */
  w12  = (w03*w12);
  /* #20: @1 = (@1-@12) */
  w01 -= w12;
  /* #21: @12 = 1 */
  w12 = 1.;
  /* #22: @0 = (@0*@14) */
  w00 *= w14;
  /* #23: @0 = (@12-@0) */
  w00  = (w12-w00);
  /* #24: @1 = (@1/@0) */
  w01 /= w00;
  /* #25: @1 = (@14*@1) */
  w01  = (w14*w01);
  /* #26: @1 = (@4-@1) */
  w01  = (w04-w01);
  /* #27: @0 = 0.00518135 */
  w00 = 5.1813471502590676e-03;
  /* #28: @15 = 2567 */
  w15 = 2567.;
  /* #29: @8 = (@15*@8) */
  w08  = (w15*w08);
  /* #30: @16 = cos(@5) */
  w16 = cos( w05 );
  /* #31: @17 = (@12+@16) */
  w17  = (w12+w16);
  /* #32: @17 = (@8*@17) */
  w17  = (w08*w17);
  /* #33: @18 = 1.737 */
  w18 = 1.7370000000000001e+00;
  /* #34: @19 = 0.517647 */
  w19 = 5.1764705882352946e-01;
  /* #35: @20 = 1893.33 */
  w20 = 1.8933300000000002e+03;
  /* #36: @21 = 1.88 */
  w21 = 1.8799999999999999e+00;
  /* #37: @22 = (@21*@2) */
  w22  = (w21*w02);
  /* #38: @22 = (@22*@2) */
  w22 *= w02;
  /* #39: @22 = (@20+@22) */
  w22  = (w20+w22);
  /* #40: @23 = (@19*@22) */
  w23  = (w19*w22);
  /* #41: @23 = (@18*@23) */
  w23  = (w18*w23);
  /* #42: @24 = 1.5 */
  w24 = 1.5000000000000000e+00;
  /* #43: @25 = 10.23 */
  w25 = 1.0230000000000000e+01;
  /* #44: @26 = 0.738 */
  w26 = 7.3799999999999999e-01;
  /* #45: @27 = (@26*@4) */
  w27  = (w26*w04);
  /* #46: @27 = (@3+@27) */
  w27  = (w03+w27);
  /* #47: @28 = 1e-08 */
  w28 = 1.0000000000000000e-08;
  /* #48: @29 = sq(@2) */
  w29 = casadi_sq( w02 );
  /* #49: @29 = (@28+@29) */
  w29  = (w28+w29);
  /* #50: @29 = sqrt(@29) */
  w29 = sqrt( w29 );
  /* #51: @27 = atan2(@27,@29) */
  w27  = atan2(w27,w29);
  /* #52: @27 = (@5-@27) */
  w27  = (w05-w27);
  /* #53: @27 = (@25*@27) */
  w27  = (w25*w27);
  /* #54: @27 = atan2(@27,@12) */
  w27  = atan2(w27,w12);
  /* #55: @27 = (@24*@27) */
  w27  = (w24*w27);
  /* #56: @27 = sin(@27) */
  w27 = sin( w27 );
  /* #57: @23 = (@23*@27) */
  w23 *= w27;
  /* #58: @27 = sin(@5) */
  w27 = sin( w05 );
  /* #59: @30 = (@23*@27) */
  w30  = (w23*w27);
  /* #60: @17 = (@17-@30) */
  w17 -= w30;
  /* #61: @30 = 193 */
  w30 = 193.;
  /* #62: @31 = (@30*@3) */
  w31  = (w30*w03);
  /* #63: @31 = (@31*@4) */
  w31 *= w04;
  /* #64: @17 = (@17+@31) */
  w17 += w31;
  /* #65: @31 = 25 */
  w31 = 25.;
  /* #66: @32 = 0.814 */
  w32 = 8.1399999999999995e-01;
  /* #67: @33 = (@32*@2) */
  w33  = (w32*w02);
  /* #68: @33 = (@33*@2) */
  w33 *= w02;
  /* #69: @33 = (@31+@33) */
  w33  = (w31+w33);
  /* #70: @17 = (@17-@33) */
  w17 -= w33;
  /* #71: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #72: @33 = 0.482353 */
  w33 = 4.8235294117647060e-01;
  /* #73: @22 = (@33*@22) */
  w22  = (w33*w22);
  /* #74: @22 = (@18*@22) */
  w22  = (w18*w22);
  /* #75: @34 = 0.792 */
  w34 = 7.9200000000000004e-01;
  /* #76: @35 = (@34*@4) */
  w35  = (w34*w04);
  /* #77: @3 = (@3-@35) */
  w03 -= w35;
  /* #78: @3 = atan2(@3,@29) */
  w03  = atan2(w03,w29);
  /* #79: @3 = (@25*@3) */
  w03  = (w25*w03);
  /* #80: @3 = (-@3) */
  w03 = (- w03 );
  /* #81: @3 = atan2(@3,@12) */
  w03  = atan2(w03,w12);
  /* #82: @3 = (@24*@3) */
  w03  = (w24*w03);
  /* #83: @3 = sin(@3) */
  w03 = sin( w03 );
  /* #84: @22 = (@22*@3) */
  w22 *= w03;
  /* #85: @8 = (@8*@27) */
  w08 *= w27;
  /* #86: @27 = (@22+@8) */
  w27  = (w22+w08);
  /* #87: @23 = (@23*@16) */
  w23 *= w16;
  /* #88: @27 = (@27+@23) */
  w27 += w23;
  /* #89: @2 = (@30*@2) */
  w02  = (w30*w02);
  /* #90: @2 = (@2*@4) */
  w02 *= w04;
  /* #91: @27 = (@27-@2) */
  w27 -= w02;
  /* #92: @27 = (@0*@27) */
  w27  = (w00*w27);
  /* #93: @2 = 0.00909091 */
  w02 = 9.0909090909090905e-03;
  /* #94: @8 = (@8+@23) */
  w08 += w23;
  /* #95: @8 = (@26*@8) */
  w08  = (w26*w08);
  /* #96: @22 = (@34*@22) */
  w22  = (w34*w22);
  /* #97: @8 = (@8-@22) */
  w08 -= w22;
  /* #98: @22 = input[1][2] */
  w22 = arg[1] ? arg[1][2] : 0;
  /* #99: @8 = (@8+@22) */
  w08 += w22;
  /* #100: @8 = (@2*@8) */
  w08  = (w02*w08);
  /* #101: @23 = -2500 */
  w23 = -2500.;
  /* #102: @5 = (@23*@5) */
  w05  = (w23*w05);
  /* #103: @4 = 100 */
  w04 = 100.;
  /* #104: @16 = (@4*@6) */
  w16  = (w04*w06);
  /* #105: @5 = (@5-@16) */
  w05 -= w16;
  /* #106: @16 = 2500 */
  w16 = 2500.;
  /* #107: @7 = (@16*@7) */
  w07  = (w16*w07);
  /* #108: @5 = (@5+@7) */
  w05 += w07;
  /* #109: @7 = input[1][0] */
  w07 = arg[1] ? arg[1][0] : 0;
  /* #110: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #111: @36 = vertcat(@13, @1, @17, @27, @8, @6, @5, @7, @3) */
  rr=w36;
  *rr++ = w13;
  *rr++ = w01;
  *rr++ = w17;
  *rr++ = w27;
  *rr++ = w08;
  *rr++ = w06;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w03;
  /* #112: @36 = (@11*@36) */
  for (i=0, rr=w36, cs=w36; i<9; ++i) (*rr++)  = (w11*(*cs++));
  /* #113: @36 = (@9+@36) */
  for (i=0, rr=w36, cr=w09, cs=w36; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #114: @11 = @36[2] */
  for (rr=(&w11), cs=w36+2; cs!=w36+3; cs+=1) *rr++ = *cs;
  /* #115: @13 = @36[1] */
  for (rr=(&w13), cs=w36+1; cs!=w36+2; cs+=1) *rr++ = *cs;
  /* #116: @1 = sin(@13) */
  w01 = sin( w13 );
  /* #117: @17 = (@11*@1) */
  w17  = (w11*w01);
  /* #118: @27 = @36[3] */
  for (rr=(&w27), cs=w36+3; cs!=w36+4; cs+=1) *rr++ = *cs;
  /* #119: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #120: @8 = (@27*@13) */
  w08  = (w27*w13);
  /* #121: @17 = (@17+@8) */
  w17 += w08;
  /* #122: @8 = @36[4] */
  for (rr=(&w08), cs=w36+4; cs!=w36+5; cs+=1) *rr++ = *cs;
  /* #123: @13 = (@11*@13) */
  w13  = (w11*w13);
  /* #124: @1 = (@27*@1) */
  w01  = (w27*w01);
  /* #125: @13 = (@13-@1) */
  w13 -= w01;
  /* #126: @1 = @36[0] */
  for (rr=(&w01), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #127: @1 = (@1*@14) */
  w01 *= w14;
  /* #128: @1 = (@12-@1) */
  w01  = (w12-w01);
  /* #129: @13 = (@13/@1) */
  w13 /= w01;
  /* #130: @14 = (@14*@13) */
  w14 *= w13;
  /* #131: @14 = (@8-@14) */
  w14  = (w08-w14);
  /* #132: @13 = @36[8] */
  for (rr=(&w13), cs=w36+8; cs!=w36+9; cs+=1) *rr++ = *cs;
  /* #133: @15 = (@15*@13) */
  w15 *= w13;
  /* #134: @13 = @36[5] */
  for (rr=(&w13), cs=w36+5; cs!=w36+6; cs+=1) *rr++ = *cs;
  /* #135: @1 = cos(@13) */
  w01 = cos( w13 );
  /* #136: @6 = (@12+@1) */
  w06  = (w12+w01);
  /* #137: @6 = (@15*@6) */
  w06  = (w15*w06);
  /* #138: @21 = (@21*@11) */
  w21 *= w11;
  /* #139: @21 = (@21*@11) */
  w21 *= w11;
  /* #140: @20 = (@20+@21) */
  w20 += w21;
  /* #141: @19 = (@19*@20) */
  w19 *= w20;
  /* #142: @19 = (@18*@19) */
  w19  = (w18*w19);
  /* #143: @21 = (@26*@8) */
  w21  = (w26*w08);
  /* #144: @21 = (@27+@21) */
  w21  = (w27+w21);
  /* #145: @5 = sq(@11) */
  w05 = casadi_sq( w11 );
  /* #146: @28 = (@28+@5) */
  w28 += w05;
  /* #147: @28 = sqrt(@28) */
  w28 = sqrt( w28 );
  /* #148: @21 = atan2(@21,@28) */
  w21  = atan2(w21,w28);
  /* #149: @21 = (@13-@21) */
  w21  = (w13-w21);
  /* #150: @21 = (@25*@21) */
  w21  = (w25*w21);
  /* #151: @21 = atan2(@21,@12) */
  w21  = atan2(w21,w12);
  /* #152: @21 = (@24*@21) */
  w21  = (w24*w21);
  /* #153: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #154: @19 = (@19*@21) */
  w19 *= w21;
  /* #155: @21 = sin(@13) */
  w21 = sin( w13 );
  /* #156: @5 = (@19*@21) */
  w05  = (w19*w21);
  /* #157: @6 = (@6-@5) */
  w06 -= w05;
  /* #158: @5 = (@30*@27) */
  w05  = (w30*w27);
  /* #159: @5 = (@5*@8) */
  w05 *= w08;
  /* #160: @6 = (@6+@5) */
  w06 += w05;
  /* #161: @32 = (@32*@11) */
  w32 *= w11;
  /* #162: @32 = (@32*@11) */
  w32 *= w11;
  /* #163: @31 = (@31+@32) */
  w31 += w32;
  /* #164: @6 = (@6-@31) */
  w06 -= w31;
  /* #165: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #166: @33 = (@33*@20) */
  w33 *= w20;
  /* #167: @18 = (@18*@33) */
  w18 *= w33;
  /* #168: @33 = (@34*@8) */
  w33  = (w34*w08);
  /* #169: @27 = (@27-@33) */
  w27 -= w33;
  /* #170: @27 = atan2(@27,@28) */
  w27  = atan2(w27,w28);
  /* #171: @25 = (@25*@27) */
  w25 *= w27;
  /* #172: @25 = (-@25) */
  w25 = (- w25 );
  /* #173: @25 = atan2(@25,@12) */
  w25  = atan2(w25,w12);
  /* #174: @24 = (@24*@25) */
  w24 *= w25;
  /* #175: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #176: @18 = (@18*@24) */
  w18 *= w24;
  /* #177: @15 = (@15*@21) */
  w15 *= w21;
  /* #178: @21 = (@18+@15) */
  w21  = (w18+w15);
  /* #179: @19 = (@19*@1) */
  w19 *= w01;
  /* #180: @21 = (@21+@19) */
  w21 += w19;
  /* #181: @30 = (@30*@11) */
  w30 *= w11;
  /* #182: @30 = (@30*@8) */
  w30 *= w08;
  /* #183: @21 = (@21-@30) */
  w21 -= w30;
  /* #184: @0 = (@0*@21) */
  w00 *= w21;
  /* #185: @15 = (@15+@19) */
  w15 += w19;
  /* #186: @26 = (@26*@15) */
  w26 *= w15;
  /* #187: @34 = (@34*@18) */
  w34 *= w18;
  /* #188: @26 = (@26-@34) */
  w26 -= w34;
  /* #189: @26 = (@26+@22) */
  w26 += w22;
  /* #190: @2 = (@2*@26) */
  w02 *= w26;
  /* #191: @26 = @36[6] */
  for (rr=(&w26), cs=w36+6; cs!=w36+7; cs+=1) *rr++ = *cs;
  /* #192: @23 = (@23*@13) */
  w23 *= w13;
  /* #193: @4 = (@4*@26) */
  w04 *= w26;
  /* #194: @23 = (@23-@4) */
  w23 -= w04;
  /* #195: @4 = @36[7] */
  for (rr=(&w04), cs=w36+7; cs!=w36+8; cs+=1) *rr++ = *cs;
  /* #196: @16 = (@16*@4) */
  w16 *= w04;
  /* #197: @23 = (@23+@16) */
  w23 += w16;
  /* #198: @36 = vertcat(@17, @14, @6, @0, @2, @26, @23, @7, @3) */
  rr=w36;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w06;
  *rr++ = w00;
  *rr++ = w02;
  *rr++ = w26;
  *rr++ = w23;
  *rr++ = w07;
  *rr++ = w03;
  /* #199: @36 = (@10*@36) */
  for (i=0, rr=w36, cs=w36; i<9; ++i) (*rr++)  = (w10*(*cs++));
  /* #200: @9 = (@9+@36) */
  for (i=0, rr=w09, cs=w36; i<9; ++i) (*rr++) += (*cs++);
  /* #201: output[0][0] = @9 */
  casadi_copy(w09, 9, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_dyn_disc_phi_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 53;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 53*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
