/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_cost_y_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {13, 1, 1};

/* frenet_centerline_runtime_cost_y_0_fun:(i0[9],i1[3],i2[0],i3[],i4[4])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #6: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #7: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #8: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #9: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #10: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #11: output[0][5] = @2 */
  if (res[0]) res[0][5] = w2;
  /* #12: @3 = input[0][6] */
  w3 = arg[0] ? arg[0][6] : 0;
  /* #13: output[0][6] = @3 */
  if (res[0]) res[0][6] = w3;
  /* #14: @3 = input[0][7] */
  w3 = arg[0] ? arg[0][7] : 0;
  /* #15: output[0][7] = @3 */
  if (res[0]) res[0][7] = w3;
  /* #16: @3 = input[0][8] */
  w3 = arg[0] ? arg[0][8] : 0;
  /* #17: output[0][8] = @3 */
  if (res[0]) res[0][8] = w3;
  /* #18: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #19: output[0][9] = @3 */
  if (res[0]) res[0][9] = w3;
  /* #20: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #21: output[0][10] = @3 */
  if (res[0]) res[0][10] = w3;
  /* #22: @3 = input[1][2] */
  w3 = arg[1] ? arg[1][2] : 0;
  /* #23: output[0][11] = @3 */
  if (res[0]) res[0][11] = w3;
  /* #24: @3 = 1e-08 */
  w3 = 1.0000000000000000e-08;
  /* #25: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #26: @3 = (@3+@0) */
  w3 += w0;
  /* #27: @3 = sqrt(@3) */
  w3 = sqrt( w3 );
  /* #28: @1 = atan2(@1,@3) */
  w1  = atan2(w1,w3);
  /* #29: @3 = 0.792 */
  w3 = 7.9200000000000004e-01;
  /* #30: @2 = tan(@2) */
  w2 = tan( w2 );
  /* #31: @3 = (@3*@2) */
  w3 *= w2;
  /* #32: @2 = 1.53 */
  w2 = 1.5300000000000000e+00;
  /* #33: @3 = atan2(@3,@2) */
  w3  = atan2(w3,w2);
  /* #34: @1 = (@1-@3) */
  w1 -= w3;
  /* #35: output[0][12] = @1 */
  if (res[0]) res[0][12] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_cost_y_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_cost_y_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_cost_y_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_cost_y_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_cost_y_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_cost_y_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_cost_y_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_cost_y_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_cost_y_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 4*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
