/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) frenet_centerline_runtime_conl_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[16] = 
  {7, 7, 0, 1, 2, 3, 4, 5,
  6, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {0, 2, 3, 4, 7, 8};
static const casadi_int casadi_s2[3] = {9, 1, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};
static const casadi_int casadi_s5[3] = {7, 1, 1};
static const casadi_int casadi_s6[3] = {0, 0, 1};
static const casadi_int casadi_s7[3] = {13, 1, 1};
static const casadi_int casadi_s8[3] = {1, 1, 1};
static const casadi_int casadi_s9[22] = 
  {12, 7, 0, 1, 2, 3, 4, 5,
  8, 12, 3, 4, 0, 1, 2, 5,
  6, 8, 3, 4, 5, 6};
static const casadi_int casadi_s10[3] = {0, 7, 1};

/* psi:(i0[7],i1[],i2[13],i3[0])->(o0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, w1, *w2=w+2, w3;
  const casadi_real *cs;
  /* #0: @0 = 0.5 */
  w0 = 5.0000000000000000e-01;
  /* #1: @1 = input[2][4] */
  w1 = arg[2] ? arg[2][4] : 0;
  /* #2: @0 = (@0*@1) */
  w0 *= w1;
  /* #3: @2 = input[0][0] */
  casadi_copy(arg[0], 7, w2);
  /* #4: @1 = @2[0] */
  for (rr=(&w1), cs=w2+0; cs!=w2+1; cs+=1) *rr++ = *cs;
  /* #5: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #6: @0 = (@0*@1) */
  w0 *= w1;
  /* #7: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #8: @3 = input[2][5] */
  w3 = arg[2] ? arg[2][5] : 0;
  /* #9: @1 = (@1*@3) */
  w1 *= w3;
  /* #10: @3 = @2[1] */
  for (rr=(&w3), cs=w2+1; cs!=w2+2; cs+=1) *rr++ = *cs;
  /* #11: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #12: @1 = (@1*@3) */
  w1 *= w3;
  /* #13: @0 = (@0+@1) */
  w0 += w1;
  /* #14: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #15: @3 = input[2][6] */
  w3 = arg[2] ? arg[2][6] : 0;
  /* #16: @1 = (@1*@3) */
  w1 *= w3;
  /* #17: @3 = @2[2] */
  for (rr=(&w3), cs=w2+2; cs!=w2+3; cs+=1) *rr++ = *cs;
  /* #18: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #19: @1 = (@1*@3) */
  w1 *= w3;
  /* #20: @0 = (@0+@1) */
  w0 += w1;
  /* #21: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #22: @3 = input[2][7] */
  w3 = arg[2] ? arg[2][7] : 0;
  /* #23: @1 = (@1*@3) */
  w1 *= w3;
  /* #24: @3 = @2[3] */
  for (rr=(&w3), cs=w2+3; cs!=w2+4; cs+=1) *rr++ = *cs;
  /* #25: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #26: @1 = (@1*@3) */
  w1 *= w3;
  /* #27: @0 = (@0+@1) */
  w0 += w1;
  /* #28: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #29: @3 = input[2][8] */
  w3 = arg[2] ? arg[2][8] : 0;
  /* #30: @1 = (@1*@3) */
  w1 *= w3;
  /* #31: @3 = @2[4] */
  for (rr=(&w3), cs=w2+4; cs!=w2+5; cs+=1) *rr++ = *cs;
  /* #32: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #33: @1 = (@1*@3) */
  w1 *= w3;
  /* #34: @0 = (@0+@1) */
  w0 += w1;
  /* #35: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #36: @3 = input[2][9] */
  w3 = arg[2] ? arg[2][9] : 0;
  /* #37: @1 = (@1*@3) */
  w1 *= w3;
  /* #38: @3 = @2[5] */
  for (rr=(&w3), cs=w2+5; cs!=w2+6; cs+=1) *rr++ = *cs;
  /* #39: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #40: @1 = (@1*@3) */
  w1 *= w3;
  /* #41: @0 = (@0+@1) */
  w0 += w1;
  /* #42: @1 = input[2][10] */
  w1 = arg[2] ? arg[2][10] : 0;
  /* #43: @3 = @2[6] */
  for (rr=(&w3), cs=w2+6; cs!=w2+7; cs+=1) *rr++ = *cs;
  /* #44: @1 = (@1*@3) */
  w1 *= w3;
  /* #45: @0 = (@0-@1) */
  w0 -= w1;
  /* #46: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* outer_loss_grad:(i0[7],i1[],i2[13],i3[0])->(o0[7]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, *w1=w+7, w2, *w3=w+15, w4, w5;
  const casadi_real *cs;
  /* #0: @0 = zeros(7x1) */
  casadi_clear(w0, 7);
  /* #1: @1 = zeros(7x1) */
  casadi_clear(w1, 7);
  /* #2: @2 = input[2][10] */
  w2 = arg[2] ? arg[2][10] : 0;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: (@1[6] += @2) */
  for (rr=w1+6, cs=(&w2); rr!=w1+7; rr+=1) *rr += *cs++;
  /* #5: @3 = input[0][0] */
  casadi_copy(arg[0], 7, w3);
  /* #6: @2 = @3[5] */
  for (rr=(&w2), cs=w3+5; cs!=w3+6; cs+=1) *rr++ = *cs;
  /* #7: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #8: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #9: @5 = input[2][9] */
  w5 = arg[2] ? arg[2][9] : 0;
  /* #10: @4 = (@4*@5) */
  w4 *= w5;
  /* #11: @2 = (@2*@4) */
  w2 *= w4;
  /* #12: (@1[5] += @2) */
  for (rr=w1+5, cs=(&w2); rr!=w1+6; rr+=1) *rr += *cs++;
  /* #13: @2 = @3[4] */
  for (rr=(&w2), cs=w3+4; cs!=w3+5; cs+=1) *rr++ = *cs;
  /* #14: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #15: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #16: @5 = input[2][8] */
  w5 = arg[2] ? arg[2][8] : 0;
  /* #17: @4 = (@4*@5) */
  w4 *= w5;
  /* #18: @2 = (@2*@4) */
  w2 *= w4;
  /* #19: (@1[4] += @2) */
  for (rr=w1+4, cs=(&w2); rr!=w1+5; rr+=1) *rr += *cs++;
  /* #20: @2 = @3[3] */
  for (rr=(&w2), cs=w3+3; cs!=w3+4; cs+=1) *rr++ = *cs;
  /* #21: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #22: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #23: @5 = input[2][7] */
  w5 = arg[2] ? arg[2][7] : 0;
  /* #24: @4 = (@4*@5) */
  w4 *= w5;
  /* #25: @2 = (@2*@4) */
  w2 *= w4;
  /* #26: (@1[3] += @2) */
  for (rr=w1+3, cs=(&w2); rr!=w1+4; rr+=1) *rr += *cs++;
  /* #27: @2 = @3[2] */
  for (rr=(&w2), cs=w3+2; cs!=w3+3; cs+=1) *rr++ = *cs;
  /* #28: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #29: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #30: @5 = input[2][6] */
  w5 = arg[2] ? arg[2][6] : 0;
  /* #31: @4 = (@4*@5) */
  w4 *= w5;
  /* #32: @2 = (@2*@4) */
  w2 *= w4;
  /* #33: (@1[2] += @2) */
  for (rr=w1+2, cs=(&w2); rr!=w1+3; rr+=1) *rr += *cs++;
  /* #34: @2 = @3[1] */
  for (rr=(&w2), cs=w3+1; cs!=w3+2; cs+=1) *rr++ = *cs;
  /* #35: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #36: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #37: @5 = input[2][5] */
  w5 = arg[2] ? arg[2][5] : 0;
  /* #38: @4 = (@4*@5) */
  w4 *= w5;
  /* #39: @2 = (@2*@4) */
  w2 *= w4;
  /* #40: (@1[1] += @2) */
  for (rr=w1+1, cs=(&w2); rr!=w1+2; rr+=1) *rr += *cs++;
  /* #41: @2 = @3[0] */
  for (rr=(&w2), cs=w3+0; cs!=w3+1; cs+=1) *rr++ = *cs;
  /* #42: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #43: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #44: @5 = input[2][4] */
  w5 = arg[2] ? arg[2][4] : 0;
  /* #45: @4 = (@4*@5) */
  w4 *= w5;
  /* #46: @2 = (@2*@4) */
  w2 *= w4;
  /* #47: (@1[0] += @2) */
  for (rr=w1+0, cs=(&w2); rr!=w1+1; rr+=1) *rr += *cs++;
  /* #48: @2 = @1[0] */
  for (rr=(&w2), cs=w1+0; cs!=w1+1; cs+=1) *rr++ = *cs;
  /* #49: (@0[0] = @2) */
  for (rr=w0+0, cs=(&w2); rr!=w0+1; rr+=1) *rr = *cs++;
  /* #50: @2 = @1[1] */
  for (rr=(&w2), cs=w1+1; cs!=w1+2; cs+=1) *rr++ = *cs;
  /* #51: (@0[1] = @2) */
  for (rr=w0+1, cs=(&w2); rr!=w0+2; rr+=1) *rr = *cs++;
  /* #52: @2 = @1[2] */
  for (rr=(&w2), cs=w1+2; cs!=w1+3; cs+=1) *rr++ = *cs;
  /* #53: (@0[2] = @2) */
  for (rr=w0+2, cs=(&w2); rr!=w0+3; rr+=1) *rr = *cs++;
  /* #54: @2 = @1[3] */
  for (rr=(&w2), cs=w1+3; cs!=w1+4; cs+=1) *rr++ = *cs;
  /* #55: (@0[3] = @2) */
  for (rr=w0+3, cs=(&w2); rr!=w0+4; rr+=1) *rr = *cs++;
  /* #56: @2 = @1[4] */
  for (rr=(&w2), cs=w1+4; cs!=w1+5; cs+=1) *rr++ = *cs;
  /* #57: (@0[4] = @2) */
  for (rr=w0+4, cs=(&w2); rr!=w0+5; rr+=1) *rr = *cs++;
  /* #58: @2 = @1[5] */
  for (rr=(&w2), cs=w1+5; cs!=w1+6; cs+=1) *rr++ = *cs;
  /* #59: (@0[5] = @2) */
  for (rr=w0+5, cs=(&w2); rr!=w0+6; rr+=1) *rr = *cs++;
  /* #60: @2 = @1[6] */
  for (rr=(&w2), cs=w1+6; cs!=w1+7; cs+=1) *rr++ = *cs;
  /* #61: (@0[6] = @2) */
  for (rr=w0+6, cs=(&w2); rr!=w0+7; rr+=1) *rr = *cs++;
  /* #62: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  return 0;
}

/* outer_hess:(i0[7],i1[],i2[13],i3[0])->(o0[7x7,6nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *w0=w+0, *w1=w+6, w2, w3, *w4=w+15;
  const casadi_real *cs;
  /* #0: @0 = zeros(7x7,6nz) */
  casadi_clear(w0, 6);
  /* #1: @1 = zeros(7x1) */
  casadi_clear(w1, 7);
  /* #2: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #3: @3 = input[2][9] */
  w3 = arg[2] ? arg[2][9] : 0;
  /* #4: @2 = (@2*@3) */
  w2 *= w3;
  /* #5: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #6: (@1[5] += @2) */
  for (rr=w1+5, cs=(&w2); rr!=w1+6; rr+=1) *rr += *cs++;
  /* #7: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #8: @3 = input[2][8] */
  w3 = arg[2] ? arg[2][8] : 0;
  /* #9: @2 = (@2*@3) */
  w2 *= w3;
  /* #10: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #11: (@1[4] += @2) */
  for (rr=w1+4, cs=(&w2); rr!=w1+5; rr+=1) *rr += *cs++;
  /* #12: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #13: @3 = input[2][7] */
  w3 = arg[2] ? arg[2][7] : 0;
  /* #14: @2 = (@2*@3) */
  w2 *= w3;
  /* #15: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #16: (@1[3] += @2) */
  for (rr=w1+3, cs=(&w2); rr!=w1+4; rr+=1) *rr += *cs++;
  /* #17: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #18: @3 = input[2][6] */
  w3 = arg[2] ? arg[2][6] : 0;
  /* #19: @2 = (@2*@3) */
  w2 *= w3;
  /* #20: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #21: (@1[2] += @2) */
  for (rr=w1+2, cs=(&w2); rr!=w1+3; rr+=1) *rr += *cs++;
  /* #22: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #23: @3 = input[2][5] */
  w3 = arg[2] ? arg[2][5] : 0;
  /* #24: @2 = (@2*@3) */
  w2 *= w3;
  /* #25: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #26: (@1[1] += @2) */
  for (rr=w1+1, cs=(&w2); rr!=w1+2; rr+=1) *rr += *cs++;
  /* #27: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #28: @3 = input[2][4] */
  w3 = arg[2] ? arg[2][4] : 0;
  /* #29: @2 = (@2*@3) */
  w2 *= w3;
  /* #30: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #31: (@1[0] += @2) */
  for (rr=w1+0, cs=(&w2); rr!=w1+1; rr+=1) *rr += *cs++;
  /* #32: @4 = @1[:6] */
  for (rr=w4, cs=w1+0; cs!=w1+6; cs+=1) *rr++ = *cs;
  /* #33: (@0[:6] = @4) */
  for (rr=w0+0, cs=w4; rr!=w0+6; rr+=1) *rr = *cs++;
  /* #34: @4 = @1[:6] */
  for (rr=w4, cs=w1+0; cs!=w1+6; cs+=1) *rr++ = *cs;
  /* #35: (@0[:6] = @4) */
  for (rr=w0+0, cs=w4; rr!=w0+6; rr+=1) *rr = *cs++;
  /* #36: @4 = @0' */
  casadi_trans(w0,casadi_s0, w4, casadi_s0, iw);
  /* #37: output[0][0] = @4 */
  casadi_copy(w4, 6, res[0]);
  return 0;
}

/* frenet_centerline_runtime_conl_cost_0_fun_jac_hess:(i0[9],i1[3],i2[0],i3[7],i4[],i5[13])->(o0,o1[7],o2[12x7,12nz],o3[0x7],o4[7x7,6nz],o5) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+6, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+44, *w21=w+51;
  casadi_real w23, w24, w25, w26, w27, *w28=w+63, *w30=w+76, *w31=w+88, *w32=w+97, *w33=w+103, *w34=w+109, *w35=w+111;
  const casadi_int *cii;
  const casadi_real **arg1=arg+6, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[1][0] */
  w02 = arg[1] ? arg[1][0] : 0;
  /* #3: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #4: @4 = input[1][2] */
  w04 = arg[1] ? arg[1][2] : 0;
  /* #5: @5 = input[0][3] */
  w05 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = 1e-08 */
  w06 = 1.0000000000000000e-08;
  /* #7: @7 = input[0][2] */
  w07 = arg[0] ? arg[0][2] : 0;
  /* #8: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #9: @6 = (@6+@8) */
  w06 += w08;
  /* #10: @8 = sqrt(@6) */
  w08 = sqrt( w06 );
  /* #11: @9 = atan2(@5,@8) */
  w09  = atan2(w05,w08);
  /* #12: @10 = 0.792 */
  w10 = 7.9200000000000004e-01;
  /* #13: @11 = input[0][5] */
  w11 = arg[0] ? arg[0][5] : 0;
  /* #14: @12 = tan(@11) */
  w12 = tan( w11 );
  /* #15: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #16: @13 = 1.53 */
  w13 = 1.5300000000000000e+00;
  /* #17: @14 = atan2(@12,@13) */
  w14  = atan2(w12,w13);
  /* #18: @9 = (@9-@14) */
  w09 -= w14;
  /* #19: @14 = cos(@1) */
  w14 = cos( w01 );
  /* #20: @15 = (@7*@14) */
  w15  = (w07*w14);
  /* #21: @16 = sin(@1) */
  w16 = sin( w01 );
  /* #22: @17 = (@5*@16) */
  w17  = (w05*w16);
  /* #23: @15 = (@15-@17) */
  w15 -= w17;
  /* #24: @17 = 1 */
  w17 = 1.;
  /* #25: @18 = input[5][0] */
  w18 = arg[5] ? arg[5][0] : 0;
  /* #26: @19 = (@0*@18) */
  w19  = (w00*w18);
  /* #27: @17 = (@17-@19) */
  w17 -= w19;
  /* #28: @15 = (@15/@17) */
  w15 /= w17;
  /* #29: @20 = vertcat(@0, @1, @2, @3, @4, @9, @15) */
  rr=w20;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w15;
  /* #30: @21 = input[3][0] */
  casadi_copy(arg[3], 7, w21);
  /* #31: @20 = (@20-@21) */
  for (i=0, rr=w20, cs=w21; i<7; ++i) (*rr++) -= (*cs++);
  /* #32: @22 = 0x0 */
  /* #33: @0 = input[5][1] */
  w00 = arg[5] ? arg[5][1] : 0;
  /* #34: @1 = input[5][2] */
  w01 = arg[5] ? arg[5][2] : 0;
  /* #35: @2 = input[5][3] */
  w02 = arg[5] ? arg[5][3] : 0;
  /* #36: @3 = input[5][4] */
  w03 = arg[5] ? arg[5][4] : 0;
  /* #37: @4 = input[5][5] */
  w04 = arg[5] ? arg[5][5] : 0;
  /* #38: @9 = input[5][6] */
  w09 = arg[5] ? arg[5][6] : 0;
  /* #39: @19 = input[5][7] */
  w19 = arg[5] ? arg[5][7] : 0;
  /* #40: @23 = input[5][8] */
  w23 = arg[5] ? arg[5][8] : 0;
  /* #41: @24 = input[5][9] */
  w24 = arg[5] ? arg[5][9] : 0;
  /* #42: @25 = input[5][10] */
  w25 = arg[5] ? arg[5][10] : 0;
  /* #43: @26 = input[5][11] */
  w26 = arg[5] ? arg[5][11] : 0;
  /* #44: @27 = input[5][12] */
  w27 = arg[5] ? arg[5][12] : 0;
  /* #45: @28 = vertcat(@18, @0, @1, @2, @3, @4, @9, @19, @23, @24, @25, @26, @27) */
  rr=w28;
  *rr++ = w18;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w09;
  *rr++ = w19;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #46: @29 = 0x1 */
  /* #47: @0 = psi(@20, @22, @28, @29) */
  arg1[0]=w20;
  arg1[1]=0;
  arg1[2]=w28;
  arg1[3]=0;
  res1[0]=(&w00);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #48: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #49: @29 = 0x1 */
  /* #50: @21 = outer_loss_grad(@20, @22, @28, @29) */
  arg1[0]=w20;
  arg1[1]=0;
  arg1[2]=w28;
  arg1[3]=0;
  res1[0]=w21;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #51: output[1][0] = @21 */
  casadi_copy(w21, 7, res[1]);
  /* #52: @30 = zeros(12x7,12nz) */
  casadi_clear(w30, 12);
  /* #53: @31 = ones(12x1,9nz) */
  casadi_fill(w31, 9, 1.);
  /* #54: {@0, @1, @2, @3, NULL, NULL, NULL, NULL, @4, NULL, NULL, NULL} = vertsplit(@31) */
  w00 = w31[0];
  w01 = w31[1];
  w02 = w31[2];
  w03 = w31[3];
  w04 = w31[5];
  /* #55: @29 = 00 */
  /* #56: @9 = 2.3409 */
  w09 = 2.3409000000000000e+00;
  /* #57: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #58: @9 = (@9+@12) */
  w09 += w12;
  /* #59: @13 = (@13/@9) */
  w13 /= w09;
  /* #60: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #61: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #62: @4 = (@4/@11) */
  w04 /= w11;
  /* #63: @10 = (@10*@4) */
  w10 *= w04;
  /* #64: @13 = (@13*@10) */
  w13 *= w10;
  /* #65: @13 = (-@13) */
  w13 = (- w13 );
  /* #66: @15 = (@15/@17) */
  w15 /= w17;
  /* #67: @18 = (@18*@3) */
  w18 *= w03;
  /* #68: @15 = (@15*@18) */
  w15 *= w18;
  /* #69: @32 = vertcat(@3, @29, @0, @1, @2, @13, @15) */
  rr=w32;
  *rr++ = w03;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w13;
  *rr++ = w15;
  /* #70: @33 = @32[:6] */
  for (rr=w33, cs=w32+0; cs!=w32+6; cs+=1) *rr++ = *cs;
  /* #71: (@30[0, 2, 3, 4, 7, 8] = @33) */
  for (cii=casadi_s1, rr=w30, cs=w33; cii!=casadi_s1+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #72: @3 = ones(12x1,1nz) */
  w03 = 1.;
  /* #73: {NULL, NULL, NULL, NULL, @0, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@3) */
  w00 = w03;
  /* #74: @3 = (@14*@0) */
  w03  = (w14*w00);
  /* #75: @3 = (@5*@3) */
  w03  = (w05*w03);
  /* #76: @3 = (-@3) */
  w03 = (- w03 );
  /* #77: @1 = (@16*@0) */
  w01  = (w16*w00);
  /* #78: @1 = (@7*@1) */
  w01  = (w07*w01);
  /* #79: @3 = (@3-@1) */
  w03 -= w01;
  /* #80: @3 = (@3/@17) */
  w03 /= w17;
  /* #81: @34 = vertcat(@29, @0, @29, @29, @29, @29, @3) */
  rr=w34;
  *rr++ = w00;
  *rr++ = w03;
  /* #82: @35 = @34[:2] */
  for (rr=w35, cs=w34+0; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #83: (@30[1:17:8] = @35) */
  for (rr=w30+1, cs=w35; rr!=w30+17; rr+=8) *rr = *cs++;
  /* #84: @0 = sq(@5) */
  w00 = casadi_sq( w05 );
  /* #85: @0 = (@0+@6) */
  w00 += w06;
  /* #86: @5 = (@5/@0) */
  w05 /= w00;
  /* #87: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #88: @6 = ones(12x1,1nz) */
  w06 = 1.;
  /* #89: {NULL, NULL, NULL, NULL, NULL, @3, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@6) */
  w03 = w06;
  /* #90: @7 = (@7*@3) */
  w07 *= w03;
  /* #91: @6 = (2.*@8) */
  w06 = (2.* w08 );
  /* #92: @7 = (@7/@6) */
  w07 /= w06;
  /* #93: @5 = (@5*@7) */
  w05 *= w07;
  /* #94: @5 = (-@5) */
  w05 = (- w05 );
  /* #95: @14 = (@14*@3) */
  w14 *= w03;
  /* #96: @14 = (@14/@17) */
  w14 /= w17;
  /* #97: @35 = vertcat(@29, @29, @29, @29, @29, @5, @14) */
  rr=w35;
  *rr++ = w05;
  *rr++ = w14;
  /* #98: @34 = @35[:2] */
  for (rr=w34, cs=w35+0; cs!=w35+2; cs+=1) *rr++ = *cs;
  /* #99: (@30[5:15:5] = @34) */
  for (rr=w30+5, cs=w34; rr!=w30+15; rr+=5) *rr = *cs++;
  /* #100: @8 = (@8/@0) */
  w08 /= w00;
  /* #101: @0 = ones(12x1,1nz) */
  w00 = 1.;
  /* #102: {NULL, NULL, NULL, NULL, NULL, NULL, @5, NULL, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w05 = w00;
  /* #103: @8 = (@8*@5) */
  w08 *= w05;
  /* #104: @16 = (@16*@5) */
  w16 *= w05;
  /* #105: @16 = (@16/@17) */
  w16 /= w17;
  /* #106: @16 = (-@16) */
  w16 = (- w16 );
  /* #107: @34 = vertcat(@29, @29, @29, @29, @29, @8, @16) */
  rr=w34;
  *rr++ = w08;
  *rr++ = w16;
  /* #108: @35 = @34[:2] */
  for (rr=w35, cs=w34+0; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #109: (@30[6:16:5] = @35) */
  for (rr=w30+6, cs=w35; rr!=w30+16; rr+=5) *rr = *cs++;
  /* #110: output[2][0] = @30 */
  casadi_copy(w30, 12, res[2]);
  /* #111: @29 = 0x1 */
  /* #112: @33 = outer_hess(@20, @22, @28, @29) */
  arg1[0]=w20;
  arg1[1]=0;
  arg1[2]=w28;
  arg1[3]=0;
  res1[0]=w33;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #113: output[4][0] = @33 */
  casadi_copy(w33, 6, res[4]);
  /* #114: @8 = 0 */
  w08 = 0.;
  /* #115: output[5][0] = @8 */
  if (res[5]) res[5][0] = w08;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void frenet_centerline_runtime_conl_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_conl_cost_0_fun_jac_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int frenet_centerline_runtime_conl_cost_0_fun_jac_hess_n_out(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_real frenet_centerline_runtime_conl_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_conl_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* frenet_centerline_runtime_conl_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    case 5: return "o5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_conl_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    case 5: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* frenet_centerline_runtime_conl_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s5;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    case 4: return casadi_s0;
    case 5: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 18;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 113;
  return 0;
}

CASADI_SYMBOL_EXPORT int frenet_centerline_runtime_conl_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 18*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 8*sizeof(casadi_int);
  if (sz_w) *sz_w = 113*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
